http_transport:
  max_idle_cons: 500
  max_idle_cons_per_host: 500
  idle_con_timeout: "30s"
  tls_handshake_timeout: "30s"
  response_header_timeout: "30s"
  expect_continue_timeout: "30s"

server:
  graceful_shutdown_time: "60s"
  http_server:
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "30s"
